# Site settings
title: Lucas Lampe
tag_text: Lucas Lampe

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
  
# Social settings
twitter_username: lucaslampe
github_username: lucaslampe
email_address: lucaslampe@gmail.com
